### PR TITLE
Reinstate patch still referenced from DAOS v2.0

### PR DESCRIPTION
**Pull request by tanabarr**
Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### CODE REVIEW

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
The preferred solution here is to reference the patch at a stable path from the daos repo, rather than adding unused patches to this repo.

**Comment by jolivier23** [comment]
@brianjmurrell the issue here is that a customer tried to build 2.0.2 (and the same issue will happen with 2.0.3) from source and could not.

**Comment by brianjmurrell** [comment]
> @brianjmurrell the issue here is that a customer tried to build 2.0.2 (and the same issue will happen with 2.0.3) from source and could not.

Ugh.  That is really bad/ugly.  We are going to have to keep this unused patch around now until all of those releases go EOL.

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
Landing this without any `Version`/`Release` bump has the potential to confuse Artifactory due to a bug in Artifactory with uploading an artifact NVR that already exists.

This needs to bump `Release:` and add a `%changelog` entry at least.

**Review by jolivier23 — APPROVED** [review]

**Comment by jolivier23** [comment]
> > @brianjmurrell the issue here is that a customer tried to build 2.0.2 (and the same issue will happen with 2.0.3) from source and could not.
> 
> Ugh. That is really bad/ugly. We are going to have to keep this unused patch around now until all of those releases go EOL.

Yeah, this is due to referencing the commit via "master" rather than a githash.   We are learning some lessons.   Upstream is better for sure.

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
