### PR TITLE
Build with perf binaries in main package.

### PR DESCRIPTION
**Pull request by tanabarr**
Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### CODE REVIEW

**Comment by tanabarr** [comment]
https://jira.hpdd.intel.com/browse/DAOS-8117 requests this change

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Review by JohnMalmberg — COMMENTED** [review]
Do we need to update the Ubuntu build?

**Comment by tanabarr** [comment]
> Do we need to update the Ubuntu build?

I'm afraid I don't know how.

**Review by dpquigl — APPROVED** [review]
LGTM

**Review by JohnMalmberg — APPROVED** [review]
We will need to update Ubuntu at a later time.

**Comment by tanabarr** [comment]
https://jira.hpdd.intel.com/browse/DAOS-8117

**Pull request merged**
